# Generated by Django 5.0.1 on 2026-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences_show_inline_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_conversation_summary',
            field=models.BooleanField(default=True, help_text='If True, long recordings split by the 240s cap are automatically summarized into one conversation summary. If False, the pipeline skips summarization and the raw entries are kept exactly as recorded.'),
        ),
    ]
