# Generated by Django 5.0.1 on 2026-09-13 08:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('conversation_type', models.CharField(choices=[('meeting', 'Meeting'), ('brainstorm', 'Brainstorm'), ('decision', 'Decision'), ('journal', 'Journal'), ('other', 'Other')], default='other', help_text="Which kind of conversation this template targets. 'meeting' is the most common case in practice.", max_length=20)),
                ('system_prompt', models.TextField(help_text='Framing + rules given to the model, including the response schema.')),
                ('user_prompt', models.TextField(help_text='The message carrying the transcript. Placeholders: {{transcript}}, {{clip_count}}, {{duration_minutes}}, {{started_at}}, {{ended_at}}, {{language}}, {{user_name}}')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when no template matches the detected conversation type.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summary prompt template',
                'verbose_name_plural': 'Summary prompt templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SummaryExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text="Short human label, e.g. 'meeting with action items'.", max_length=100)),
                ('input_excerpt', models.TextField(help_text='Transcript excerpt shown to the model as the example input.')),
                ('expected_output', models.TextField(help_text='The exact JSON the model should produce for that input.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='conversation_summarizer.summaryprompttemplate')),
            ],
            options={
                'verbose_name': 'Summary example',
                'verbose_name_plural': 'Summary examples',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryAgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_global', models.BooleanField(default=False, help_text='True for the single cluster-wide default row (user must be empty).')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for this scope. A user is only summarized when their own preference (UserPreferences.enable_conversation_summary) AND this flag are both true.')),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_output_tokens', models.PositiveIntegerField(default=700)),
                ('cap_seconds', models.PositiveIntegerField(default=240, help_text="Recording cap. A clip at/over this length means 'long conversation'.")),
                ('cap_tolerance', models.FloatField(default=0.5, help_text='Seconds of slack when testing the cap. Real data contains clips slightly over 240s — never test for exact equality.')),
                ('quiet_seconds', models.PositiveIntegerField(default=600, help_text='A session whose last clip ended longer ago than this is considered finished even if no short tail clip ever arrived.')),
                ('min_chars', models.PositiveIntegerField(default=200, help_text='Skip sessions whose combined transcript is shorter than this.')),
                ('chunk_chars', models.PositiveIntegerField(default=60000, help_text='Transcripts above this size are summarized chunk-by-chunk (map-reduce).')),
                ('map_reduce_enabled', models.BooleanField(default=True)),
                ('language_policy', models.CharField(choices=[('source', 'Same as the transcript'), ('stored', "User's stored language")], default='source', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Leave empty for the global default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_agent_configs', to=settings.AUTH_USER_MODEL)),
                ('default_template', models.ForeignKey(blank=True, help_text='Template used when the conversation type has no specific template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_as_default', to='conversation_summarizer.summaryprompttemplate')),
            ],
            options={
                'verbose_name': 'Summary agent configuration',
                'verbose_name_plural': 'Summary agent configurations',
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_group_id', models.UUIDField(help_text='Shared UUID of the clips this summary covers')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('conversation_type', models.CharField(blank=True, choices=[('meeting', 'Meeting'), ('brainstorm', 'Brainstorm'), ('decision', 'Decision'), ('journal', 'Journal'), ('other', 'Other')], default='', max_length=20)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('structured_data', models.JSONField(blank=True, help_text='Full parsed JSON response: type, title, summary, key_points, decisions, action_items, people, language.', null=True)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('clip_count', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1, help_text='Incremented each time the session is (re)summarized.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_summaries', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='conversation_summarizer.summaryprompttemplate')),
            ],
            options={
                'verbose_name': 'Conversation summary',
                'verbose_name_plural': 'Conversation summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_group_id', models.UUIDField(blank=True, null=True)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('kind', models.CharField(default='summarize', help_text="'summarize' or 'map_reduce_chunk'.", max_length=20)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='conversation_summarizer.conversationsummary')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='conversation_summarizer.summaryprompttemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summary run',
                'verbose_name_plural': 'Summary runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='summaryagentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='uniq_summary_agent_config_per_user'),
        ),
        migrations.AddConstraint(
            model_name='summaryagentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('is_global',), name='uniq_global_summary_agent_config'),
        ),
        migrations.AddConstraint(
            model_name='summaryagentconfig',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_global', True), ('user__isnull', True)), models.Q(('is_global', False), ('user__isnull', False)), _connector='OR'), name='summary_agent_config_scope_exclusive'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['user', 'created_at'], name='conversatio_user_id_62cb58_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationsummary',
            constraint=models.UniqueConstraint(fields=('user', 'recording_group_id'), name='uniq_user_conversation_summary_group'),
        ),
        migrations.AddIndex(
            model_name='summaryrun',
            index=models.Index(fields=['user', 'created_at'], name='conversatio_user_id_90cc99_idx'),
        ),
    ]
