# Generated by Django 5.0.1 on 2026-09-01 17:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_recording_duration_and_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingGroupSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_group_id', models.UUIDField(help_text='Shared UUID of the group of clips this summary covers')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('clip_count', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_group_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ingestion_r_user_id_aec89c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recordinggroupsummary',
            constraint=models.UniqueConstraint(fields=('user', 'recording_group_id'), name='uniq_user_recording_group_summary'),
        ),
    ]
